### ISSUE TITLE
Enable -d option on assign

### ISSUE THREAD

**Issue by BrandonDusseau** [JohnMaguire/wbc#19]
URLs and clients should be able to be unassigned from lists. Currently the only way to remove a URL from a list is to delete the URL which removes it from all lists. Clients are attached to the list until either the client or the list is deleted.

**Comment by johnmaguire** [comment]
Closed as a part of #12. You can just assign it to the Default list.

**Comment by johnmaguire** [comment]
Never mind, this is a little different. You can have a URL in multiple lists so this does need to be a thing.
